#pragma once

//#define HOMECHESS_MODULE_PATH  _T("E:\\Lessons\\HCGraph\\debug\\HCGraph.dll")
#define HOMECHESS_MODULE_PATH  _T("HCGraph.dll")

#define HOMECHESS_WHITE_BISHOP          102
#define HOMECHESS_WHITE_KNIGHT          103
#define HOMECHESS_WHITE_ROOK            104
#define HOMECHESS_WHITE_QUEEN           105
#define HOMECHESS_WHITE_KING            106
#define HOMECHESS_BLACK_PAWN            107
#define HOMECHESS_BLACK_BISHOP          109
#define HOMECHESS_BLACK_ROOK            110
#define HOMECHESS_BLACK_QUEEN           111
#define HOMECHESS_BLACK_KING            112
#define HOMECHESS_BOARD                 113
#define HOMECHESS_BLACK_KNIGHT          115
#define HOMECHESS_WHITE_PAWN            116

#define HOMECHESS_HIGHLIGTH_WHITE_PAWN  117
#define HOMECHESS_HIGHLIGTH_WHITE_KNIGHT 118
#define HOMECHESS_HIGHLIGTH_WHITE_BISHOP 119
#define HOMECHESS_HIGHLIGTH_WHITE_ROOK  120
#define HOMECHESS_HIGHLIGTH_WHITE_QUEEN 121
#define HOMECHESS_HIGHLIGTH_WHITE_KING  122
#define HOMECHESS_HIGHLIGTH_BLACK_PAWN  123
#define HOMECHESS_HIGHLIGTH_BLACK_KNIGHT 125
#define HOMECHESS_HIGHLIGTH_BLACK_BISHOP 126
#define HOMECHESS_HIGHLIGTH_BLACK_ROOK  127
#define HOMECHESS_HIGHLIGTH_BLACK_QUEEN 128
#define HOMECHESS_HIGHLIGTH_BLACK_KING  129

#define HOMECHESS_DROPPED_WHITE_PAWN    130
#define HOMECHESS_DROPPED_WHITE_KNIGHT  131
#define HOMECHESS_DROPPED_WHITE_BISHOP  132
#define HOMECHESS_DROPPED_WHITE_ROOK    133
#define HOMECHESS_DROPPED_WHITE_QUEEN   134
#define HOMECHESS_DROPPED_WHITE_KING    135
#define HOMECHESS_DROPPED_BLACK_PAWN    136
#define HOMECHESS_DROPPED_BLACK_KNIGHT  137
#define HOMECHESS_DROPPED_BLACK_BISHOP  138
#define HOMECHESS_DROPPED_BLACK_ROOK    139
#define HOMECHESS_DROPPED_BLACK_QUEEN   140
#define HOMECHESS_DROPPED_BLACK_KING    141