#pragma once

//#define HOMECHESS_MODULE_PATH  _T("E:\\Lessons\\HCGraph\\debug\\HCGraph.dll")
#define HOMECHESS_MODULE_PATH  _T("HCGraph.dll")


#define HOMECHESS_BOARD                 176

#define HOMECHESS_WHITE_BISHOP          148
#define HOMECHESS_WHITE_KNIGHT          150
#define HOMECHESS_WHITE_ROOK            140
#define HOMECHESS_WHITE_QUEEN           151
#define HOMECHESS_WHITE_KING            149
#define HOMECHESS_BLACK_PAWN            146
#define HOMECHESS_BLACK_BISHOP          141
#define HOMECHESS_BLACK_ROOK            145
#define HOMECHESS_BLACK_QUEEN           144
#define HOMECHESS_BLACK_KING            142
#define HOMECHESS_BLACK_KNIGHT          143
#define HOMECHESS_WHITE_PAWN            147

#define HOMECHESS_HIGHLIGTH_WHITE_PAWN  159
#define HOMECHESS_HIGHLIGTH_WHITE_KNIGHT 162
#define HOMECHESS_HIGHLIGTH_WHITE_BISHOP 160
#define HOMECHESS_HIGHLIGTH_WHITE_ROOK  152
#define HOMECHESS_HIGHLIGTH_WHITE_QUEEN 163
#define HOMECHESS_HIGHLIGTH_WHITE_KING  161
#define HOMECHESS_HIGHLIGTH_BLACK_PAWN  158
#define HOMECHESS_HIGHLIGTH_BLACK_KNIGHT 155
#define HOMECHESS_HIGHLIGTH_BLACK_BISHOP 153
#define HOMECHESS_HIGHLIGTH_BLACK_ROOK  157
#define HOMECHESS_HIGHLIGTH_BLACK_QUEEN 156
#define HOMECHESS_HIGHLIGTH_BLACK_KING  154

#define HOMECHESS_DROPPED_WHITE_PAWN    171
#define HOMECHESS_DROPPED_WHITE_KNIGHT  174
#define HOMECHESS_DROPPED_WHITE_BISHOP  172
#define HOMECHESS_DROPPED_WHITE_ROOK    164
#define HOMECHESS_DROPPED_WHITE_QUEEN   175
#define HOMECHESS_DROPPED_WHITE_KING    173
#define HOMECHESS_DROPPED_BLACK_PAWN    170
#define HOMECHESS_DROPPED_BLACK_KNIGHT  167
#define HOMECHESS_DROPPED_BLACK_BISHOP  165
#define HOMECHESS_DROPPED_BLACK_ROOK    169
#define HOMECHESS_DROPPED_BLACK_QUEEN   168
#define HOMECHESS_DROPPED_BLACK_KING    166